apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  restartPolicy: OnFailure

  containers:
  - name: producer
    command:
    - sh
    - -c
    - echo Container running > /data/out
    image: trion/curl:1
    resources: {}
    volumeMounts:
    - name: data
      mountPath: /data

  - name: consumer
    command:
    - sh
    - -c
    - sleep 2; cat /input/out
    image: trion/curl:1
    resources: {}
    volumeMounts:
    - name: data
      mountPath: /input

  volumes:
  - name: data
    emptyDir: {}