apiVersion: v1
kind: Pod
metadata:
  name: cm-demo
spec:
  restartPolicy: OnFailure
  containers:
  - name: consumer
    command:
    - sh
    - -c
    - env; ls -l /config; sleep 1h 
    image: trion/curl:1
    resources: {}
    volumeMounts:
    - name: data
      mountPath: /config

    env:
    - name: FOO
      valueFrom:
        configMapKeyRef:
          name: cfg
          key: foo

  volumes:
  - name: data
    configMap:
      name: cfg