apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  restartPolicy: OnFailure
  initContainers:
  - name: producer
    command:
    - sh
    - -c
    - echo Container running > /data/out
    image: trion/curl:1
    resources: {}
    volumeMounts:
    - name: data
      mountPath: /data
  
  containers:
  - name: consumer
    command:
    - sh
    - -c
    - cat /input/out
    image: trion/curl:1
    resources: {}
    volumeMounts:
    - name: data
      mountPath: /input

  volumes:
  - name: data
    emptyDir: {}