apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data
    type: DirectoryOrCreate
    